language: ruby
rvm:
  - 2.0.0
  - 2.1.5
  - 2.2.2
before_install: gem install bundler -v 1.10.5
addons:
  code_climate:
    repo_token:
      secure: 34a046d09fe4529a3bda6a43103041d6ae93a24630737ad21ee2ce32daacbee5
