language: ruby
rvm:
  - 2.0.0
  - 2.1.5
  - 2.2.2
before_install: gem install bundler -v 1.10.5
addons:
  code_climate:
    repo_token:
      secure: 3c0a38daec04e8d951665de52bba00cf631baa154bd9a19394dcfe1fb9e85ff1
