module Fasterer::Github
  class TestData
    class << self
      def content64_with_offences
        "aC5tZXJnZSEoaXRlbTogMSwgaXRlbTI6IDMpCgpoLm1lcmdlIQoKaC5tZXJn\nZSEoaXRlbSwgaXRlbTogMSkKCmgubWVyZ2UoaXRlbTogMSkKCkVOVU0uZWFj\naF93aXRoX29iamVjdCh7fSkgZG8gfGUsIGh8CiAgaC5tZXJnZSEoZSA9PiBl\nKQplbmQKCkVOVU0uZWFjaF93aXRoX29iamVjdCh7fSkgZG8gfGUsIGh8CiAg\naFtlXSA9IGUKZW5kCgpoLm1lcmdlIShpdGVtOiAxKQoKaC5tZXJnZSEoe2l0\nZW06IDF9KQoKaC5tZXJnZSEoe30pCgpIQVNIID0geyA6d3JpdGluZyA9PiA6\nZmFzdF9ydWJ5IH0KCmRlZiBzbG93CiAgSEFTSC5mZXRjaCg6d3JpdGluZywg\nWyoxLi4xMDBdKQplbmQKCmRlZiBmYXN0CiAgSEFTSC5mZXRjaCg6d3JpdGlu\nZykgeyBbKjEuLjEwMF0gfQplbmQKCkhBU0guZmV0Y2goOndyaXRpbmcpCg==\n"
      end
    end
  end
end
